## <center>Pandas入门</center>

In [3]:
# Pandas install
!pip install pandas

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


## 1. Pandas Series

### 1.1 Series创建

**1.1.1 列表创建**

In [20]:
import pandas as pd
# pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
lst = [1,2,3,4,5]
s = pd.Series(lst)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [21]:
# 自定义索引
lst = [1,2,3,4,5,6]
s = pd.Series(lst,index=["A","B","C","D","E","F"])
s

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

**1.1.2 NumPy创建**

In [3]:
import numpy as np
s = pd.Series(np.random.random(3),index=['a','b','c'])
print(s)

a    0.035295
b    0.527418
c    0.216663
dtype: float64


**1.1.3 字典创建**

In [4]:
my_dict = {"A":1,"B":2,"C":3,"D":2}
s = pd.Series(my_dict)
print(s)

A    1
B    2
C    3
D    2
dtype: int64


### 1.2 Series索引和切片

**1.2.1 Series隐式索引的操作**

In [23]:
lst = [-1,34,52,45,-10,96]
s = pd.Series(lst)
print(s[0])  #取一行
print(type(s[0]))
print('************')
print(s[[0,1]])  #取多行
print(type(s[[0,1]]))
print('***********')
print(s[0:2])  #切片操作
print(s.iloc[0:2])  #使用iloc来专门对隐式索引进行相关操作
print(type(s.iloc[0:2]))
print('***********')
print(s.iloc[[0,1]])  #使用iloc来进行多行抽取
print(s.iloc[0])
print(type(s.iloc[0]))

-1
<class 'numpy.int64'>
************
0    -1
1    34
dtype: int64
<class 'pandas.core.series.Series'>
***********
0    -1
1    34
dtype: int64
0    -1
1    34
dtype: int64
<class 'pandas.core.series.Series'>
***********
0    -1
1    34
dtype: int64
-1
<class 'numpy.int64'>


**1.2.2 显式索引的操作**

In [24]:
lst = [-1,34,52,45,-10,96]
s = pd.Series(lst,index=["A","B","C","D","E","F"])
print(s["A"])
print(s[["A","B"]])
print(s["A":"D"])
print(s.loc["A":"E"])
print(s.loc[["A","B"]])

-1
A    -1
B    34
dtype: int64
A    -1
B    34
C    52
D    45
dtype: int64
A    -1
B    34
C    52
D    45
E   -10
dtype: int64
A    -1
B    34
dtype: int64


## 1.3 Series的基本操作

**1.3.1 数据显式**

In [25]:
lst = [-1,34,52,45,-10,96]
s = pd.Series(lst,index=["A","B","C","D","E","F"])
print(s.head(2))  # 显示前2行，默认5行
print(s.tail(3))  # 显示后3行，默认5行

A    -1
B    34
dtype: int64
D    45
E   -10
F    96
dtype: int64


**1.3.2 Series去重操作**

In [31]:
my_dict = {"A":1,"B":2,"C":3,"D":2}
s = pd.Series(my_dict)
print(s.unique())
print(type(s.unique()))

[1 2 3]
<class 'numpy.ndarray'>


In [37]:
s2 = s.drop_duplicates()  # 查看文档
s2

A    1
B    2
C    3
dtype: int64

**1.3.3 Series的相加运算**

In [57]:
# s1
lst = [1,3,5,6,10,23]
s1 = pd.Series(lst,index=["A","B","C","D","E","F"])
# s2
my_dict = {"A":1,"B":2,"C":3,"D":2}
s2 = pd.Series(my_dict)

s3 = s2+s1
print(s3)

A    2.0
B    5.0
C    8.0
D    8.0
E    NaN
F    NaN
dtype: float64


In [44]:
s2 - s1

A    0.0
B   -1.0
C   -2.0
D   -4.0
E    NaN
F    NaN
dtype: float64

**1.3.4 Series缺失值操作**

In [45]:
print(s3.notnull())  # 不为空返回True，为空返回False
print('**********')
print(s3.isnull())  # 不为空返回False，为空返回True

A     True
B     True
C     True
D     True
E    False
F    False
dtype: bool
**********
A    False
B    False
C    False
D    False
E     True
F     True
dtype: bool


## Series练习

In [46]:
# 练习1：从列表创建 Series，[1,2,3,4]
arr = [0, 1, 2, 3, 4]
s = pd.Series(arr)

In [47]:
# 练习2：从字典创建 Series，{'a':1,'b':2,'c':3,'d':4}
d = {'a':1,'b':2,'c':3,'d':4}
s = pd.Series(d)

In [48]:
# 练习3：创建一个Series，并命名Series_1
s = pd.Series(['A','B','C'])
s.name = 'Series_1'

In [50]:
# 练习4：创建夜歌Series，并展示它的values
s = pd.Series(['A','B','C'])
s.values

array(['A', 'B', 'C'], dtype=object)

In [51]:
# 练习5：给已经创建的Series添加index
s = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']
s.index = index_names

In [54]:
# 练习6：展示Series第一个元素 （请使用多种方法）
s = pd.Series(['A','B','C'], index=['first', 'second', 'third'])
print(s.iloc[0])
print(s['first'])
print(s.head(1)[0])
print(s[0])

A
A
A
A


In [55]:
# 练习7：展示除首位外所有的元素
s = pd.Series(['A','B','C','D','E'], index=['first','second','third','forth','fifth'])
s[1:-1]
s.iloc[1:-1]

second    B
third     C
forth     D
dtype: object

In [60]:
# 练习8：反转Series
s = pd.Series(['A','B','C','D','E'], index=['first','second','third','forth','fifth'])
s[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

In [58]:
# 练习9：只显示s3中不为空的行
# code here
# s1
lst = [1,3,5,6,10,23]
s1 = pd.Series(lst,index=["A","B","C","D","E","F"])
# s2
my_dict = {"A":1,"B":2,"C":3,"D":2}
s2 = pd.Series(my_dict)
s3 = s1 + s2

s3[s3.notnull()]

A    2.0
B    5.0
C    8.0
D    8.0
dtype: float64

In [59]:
# 练习10：只显示s3中为空的行
# code here
s3[s3.isnull()]

E   NaN
F   NaN
dtype: float64

## 2. Pandas DataFrame

### 2.1 DataFrame创建方式

**2.1.1 使用ndarry创建**

In [61]:
#  DataFrame的参数组成 pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
# index指定行索引，columns指定列索引，若不写，则默认从0开始，size指定行数和列数
df = pd.DataFrame(data=np.random.randint(1, 10, size=(2,4)),index=["a","b"],columns=["A","B","C","D"])
df

A  B  C  D
a  5  1  2  4
b  7  2  7  2

**2.1.2 使用字典创建**

In [62]:
dic = {"num":["4","24","65"],"size":[34,65,76]}
# key为列的索引，行索引则默认从0开始
pd.DataFrame(dic)

num  size
0   4    34
1  24    65
2  65    76

### 2.2 DataFrame的索引和切片

**2.2.1 隐式索引的操作**

In [15]:
df = pd.DataFrame(data=np.random.random((3, 4)))
df

0         1         2         3
0  0.647638  0.606136  0.983271  0.415126
1  0.309334  0.920150  0.758280  0.994708
2  0.323261  0.083222  0.447059  0.008440

In [16]:
print(df[0][0])  # 获取隐式索引单个元素
print(type(df[0][0]))
print('**********')
print(df[0:2])  # 对行的切片操作
print(type(df[0:2]))
print('**********')
print(df[[0,1]])  # 对列的操作
print(type(df[[0,1]]))
print('**********')
# iloc对于隐式索引的操作
print(df.iloc[0:2,0:2])
print('**********')
print(df.iloc[[0,1],[0,1]])

0.6476379196870508
<class 'numpy.float64'>
**********
          0         1         2         3
0  0.647638  0.606136  0.983271  0.415126
1  0.309334  0.920150  0.758280  0.994708
<class 'pandas.core.frame.DataFrame'>
**********
          0         1
0  0.647638  0.606136
1  0.309334  0.920150
2  0.323261  0.083222
<class 'pandas.core.frame.DataFrame'>
**********
          0         1
0  0.647638  0.606136
1  0.309334  0.920150
**********
          0         1
0  0.647638  0.606136
1  0.309334  0.920150


**2.2.2 显式索引的操作**

In [17]:
df = pd.DataFrame(data=np.random.random((3, 4)), index=["a","b","c"], columns=["A","B","C","D"])
df

A         B         C         D
a  0.523318  0.074977  0.447353  0.493846
b  0.264171  0.660597  0.148176  0.090777
c  0.221551  0.789645  0.964851  0.654002

In [63]:
print(df['A'])  # 获取单列
print(df.A)
print(type(df['A']))
print('**********')
print(df['A']['a'])  # 获取单个元素
print(type(df['A']['a']))
print('**********')
print(df["a":"b"])  # 获取是a到b行
print(type(df["a":"b"]))
print('**********')
print(df[["A","B"]])  # 获取A列和B列
print('**********')
print(df.loc["a":"b","A":"B"])  # loc对于显式索引的操作
print('**********')
print(df.loc[["a","b"],["A","B"]])  # loc对于显式索引的操作

a    5
b    7
Name: A, dtype: int32
a    5
b    7
Name: A, dtype: int32
<class 'pandas.core.series.Series'>
**********
5
<class 'numpy.int32'>
**********
   A  B  C  D
a  5  1  2  4
b  7  2  7  2
<class 'pandas.core.frame.DataFrame'>
**********
   A  B
a  5  1
b  7  2
**********
   A  B
a  5  1
b  7  2
**********
   A  B
a  5  1
b  7  2


**2.2.3 DataFrame的属性**

In [65]:
df = pd.DataFrame(data=np.random.random((3, 4)), index=["a","b","c"], columns=["A","B","C","D"])
df

A         B         C         D
a  0.008471  0.087974  0.631494  0.283697
b  0.464139  0.125105  0.351936  0.407667
c  0.715703  0.142511  0.495451  0.154838

In [66]:
df.values

array([[0.00847075, 0.08797363, 0.63149412, 0.28369727],
       [0.46413908, 0.12510486, 0.35193598, 0.40766652],
       [0.71570274, 0.14251104, 0.49545114, 0.15483823]])

In [67]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [68]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
df.shape

(3, 4)

In [70]:
df.size

12

### 2.3 DataFrame的级联与合并

**2.3.1 级联**  
根据指定的行或列进行值的拼接，不参与任何计算，只是把多个df变成1个

____
**pd.concat()**

In [71]:
# pd.concat()参数(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)
?pd.concat

In [76]:
dic1 = {'A': ['A0', 'A1', 'A2', 'A3'],
       'B': ['B0', 'B1', 'B2', 'B3'],
       'C': ['C0', 'C1', 'C2', 'C3'],
       'D': ['D0', 'D1', 'D2', 'D3']}

dic2 = {'A': ['A4', 'A5', 'A6', 'A7'],
        'B': ['B4', 'B5', 'B6', 'B7'],
        'C': ['C4', 'C5', 'C6', 'C7'],
        'D': ['D4', 'D5', 'D6', 'D7']}

dic3 = {'A': ['A8', 'A9', 'A10', 'A11'],
        'B': ['B8', 'B9', 'B10', 'B11'],
        'C': ['C8', 'C9', 'C10', 'C11'],
        'D': ['D8', 'D9', 'D10', 'D11']}

df1 = pd.DataFrame(dic1,index=[0, 1, 2, 3])
df2 = pd.DataFrame(dic2, index=[4, 5, 6, 7])
df3 = pd.DataFrame(dic3, index=[8, 9, 10, 11])

pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [75]:
# axis参数的用法
df = pd.concat([df1,df2,df3],keys=['x', 'y', 'z'], axis=1)
print(df)
print('********************')
print(df['x'][:4])
# 问题：用其他方式还原出df2

      x                   y                   z               
      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11
********************
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3


In [73]:
# ignore_index的用法
dic4={'a':[1,2,3,4],'b':[5,6,7,8]}
df4 = pd.DataFrame(dic4)
print(df4)
print('*'*20)
print(pd.concat([df1,df4], axis=0, ignore_index=True))
print('*'*20)
print(pd.concat([df1,df4], axis=0, ignore_index=False))

   a  b
0  1  5
1  2  6
2  3  7
3  4  8
********************
     A    B    C    D    a    b
0   A0   B0   C0   D0  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN
4  NaN  NaN  NaN  NaN  1.0  5.0
5  NaN  NaN  NaN  NaN  2.0  6.0
6  NaN  NaN  NaN  NaN  3.0  7.0
7  NaN  NaN  NaN  NaN  4.0  8.0
********************
     A    B    C    D    a    b
0   A0   B0   C0   D0  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN
0  NaN  NaN  NaN  NaN  1.0  5.0
1  NaN  NaN  NaN  NaN  2.0  6.0
2  NaN  NaN  NaN  NaN  3.0  7.0
3  NaN  NaN  NaN  NaN  4.0  8.0


In [93]:
# join的用法
dic5={'a':[1,2,3,4],'b':[5,6,7,8]}
df5= pd.DataFrame(dic5,index=[2,3,4,5])
print(df5)
print('*'*20)
print(pd.concat([df1,df5],axis=1,join='outer'))  # 取并集
print('*'*20)
print(pd.concat([df1,df5],axis=1,join='inner'))  # 取交集

   a  b
2  1  5
3  2  6
4  3  7
5  4  8
********************
    A1   B1   C1   D1    a    b
0   A0   B0   C0   D0  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN
2   A2   B2   C2   D2  1.0  5.0
3   A3   B3   C3   D3  2.0  6.0
4  NaN  NaN  NaN  NaN  3.0  7.0
5  NaN  NaN  NaN  NaN  4.0  8.0
********************
   A1  B1  C1  D1  a  b
2  A2  B2  C2  D2  1  5
3  A3  B3  C3  D3  2  6


____
**df.append()**

In [94]:
print(df1)
print('*'*20)
print(df2)
print('*'*20)
print(df1.append(df2))
print('*'*20)
print(df1)

   A1  B1  C1  D1
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
********************
   A2  B2  C2  D2
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
********************
    A1   B1   C1   D1   A2   B2   C2   D2
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7
********************
   A1  B1  C1  D1
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3


C:\Users\36332\AppData\Local\Temp\ipykernel_15600\1869521902.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df1.append(df2))


**2.3.2 合并** 

In [74]:
my_dict1 = {"ticker":["AAPL","IBM","AMZ","AMD"],"price":[123,23,34,143]}
my_dict2 = {"ticker":["AAPL","IBM","AMZ","AMD"],"buy":["T","F","T","T"]}
df1 = pd.DataFrame(my_dict1)
df2 = pd.DataFrame(my_dict2)
print(pd.merge(df1,df2))  # name一列相同，自动连接
print(pd.merge(df1,df2,on="ticker"))

  ticker  price buy
0   AAPL    123   T
1    IBM     23   F
2    AMZ     34   T
3    AMD    143   T
  ticker  price buy
0   AAPL    123   T
1    IBM     23   F
2    AMZ     34   T
3    AMD    143   T


In [109]:
my_dict1 = {"ticker":["AAPL","IBM","AMZ","AMD"],"price":[123,23,34,143], 'id': [1, 4352, 2543, 6546]}
my_dict2 = {"ticker":["AAPL","IBM","AMZ"],"buy":["T","F","T"], 'smci': [1231, 4352, 2543]}
df1 = pd.DataFrame(my_dict1)
df2 = pd.DataFrame(my_dict2)
print(df1)
print(df2)
print(pd.merge(df1,df2, left_on="id",right_on="smci"))
# SQL: select * from my_dict1 d1 left join my_dict2 d2 on d1.dep_id = d2.id

  ticker  price    id
0   AAPL    123     1
1    IBM     23  4352
2    AMZ     34  2543
3    AMD    143  6546
  ticker buy  smci
0   AAPL   T  1231
1    IBM   F  4352
2    AMZ   T  2543
  ticker_x  price    id ticker_y buy  smci
0      IBM     23  4352      IBM   F  4352
1      AMZ     34  2543      AMZ   T  2543


In [169]:
?pd.merge

In [111]:
pd.merge(df1, df2, left_on="id", right_index=True)

ticker_x  price  id ticker_y buy  smci
0     AAPL    123   1      IBM   F  4352

## DataFrame练习

In [78]:
# 练习1：创建一个DataFrame
# code here
data = np.random.random((3, 4))
df = pd.DataFrame(data)

In [ ]:
# 练习2：给这个DataFrame添加names
# code here
data = np.random.random((3, 4))
df = pd.DataFrame(data)
df.names = 'practice'

In [119]:
# 练习3：给这个DataFrame添加自己的index和column
# code here
data = np.random.random((3, 4))
df = pd.DataFrame(data)
index = ['a', 'b', 'c']
column = ['first', 'second', 'third', 'fourth']
df.index = index
df.columns = column

In [84]:
# 练习4：展示最后一行
# code here
data = np.random.random((3, 4))
df = pd.DataFrame(data)
df[-1:]
df.iloc[-1:, ...]

0         1         2         3
2  0.592199  0.055911  0.414739  0.126832

In [170]:
# 练习5：将第四列第一行赋值为10，列中其他为0
# code here
data = np.random.random((3, 4))
index = ['a', 'b', 'c']
columns = ['first', 'second', 'third', 'fourth']
df = pd.DataFrame(data, index=index, columns=columns)
df['fourth']['b':] = 0
df['fourth']['a'] = 10

In [171]:
df

first    second     third  fourth
a  0.658170  0.135528  0.982334    10.0
b  0.926898  0.237525  0.500713     0.0
c  0.926936  0.520024  0.160830     0.0

In [176]:
# 练习6：得到一个mask，条件为value为0
# 复用第五题答案
df[df['fourth'] == 0]

first    second     third  fourth
b  0.926898  0.237525  0.500713     0.0
c  0.926936  0.520024  0.160830     0.0

In [110]:
# 练习7：取出第三列的值大于0.5的所在行
data = np.random.random((3, 4))
index = ['a', 'b', 'c']
columns = ['first', 'second', 'third', 'fourth']
df = pd.DataFrame(data, index=index, columns=columns)
df[df['third'] > 0.5]

first    second     third    fourth
b  0.097137  0.458163  0.584329  0.324403
c  0.380314  0.083513  0.885202  0.665277

In [113]:
df

first    second     third    fourth
a  0.971925  0.325774  0.428189  0.301503
b  0.097137  0.458163  0.584329  0.324403
c  0.380314  0.083513  0.885202  0.665277

In [118]:
# 练习8：计算第三列总和，以及第二行总和
print(df['third'].sum())
print(df.iloc[2, :].sum())

1.8977203229364394
2.014306703142476


### 2.4 DataFrame的基本操作

**2.4.1 缺失值处理**

In [178]:
non_df = pd.DataFrame(data={'A': [None, 1, 2, 3], 'B': ['a', 'a', 'a', 'a']})
print(non_df)
print(non_df['A'][0])
print(type(non_df['A'][0]))

     A  B
0  NaN  a
1  1.0  a
2  2.0  a
3  3.0  a
nan
<class 'numpy.float64'>


In [179]:
non_df.notnull()

A     B
0  False  True
1   True  True
2   True  True
3   True  True

In [182]:
non_df.notnull().all(axis=1)

0    False
1     True
2     True
3     True
dtype: bool

In [128]:
print(non_df.dropna())
print(non_df)

     A  B
1  1.0  a
2  2.0  a
3  3.0  a
     A  B
0  NaN  a
1  1.0  a
2  2.0  a
3  3.0  a


In [142]:
# 填充缺失值
print(non_df.fillna(6))
print(non_df.fillna(axis=0, method='bfill'))
print(non_df.fillna(axis=1, method='bfill'))

     A  B
0  6.0  a
1  1.0  a
2  2.0  a
3  3.0  a
     A  B
0  1.0  a
1  1.0  a
2  2.0  a
3  3.0  a
     A  B
0    a  a
1  1.0  a
2  2.0  a
3  3.0  a


**2.4.2 重复值处理**

In [127]:
df = pd.DataFrame(data={'A': [6, 1, 1, 3, 1], 'B': ['d', 'c', 'c', 'a', 'b']})
# 把所有列重复的的行标注出来
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [128]:
df.duplicated(subset=["A"])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [129]:
df.duplicated(subset=["A"], keep='last')

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [181]:
df.duplicated(subset=["A","B"],keep=False)

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [182]:
?df.drop_duplicates

In [183]:
# 删除重复行，保留唯一值
df.drop_duplicates()

A  B
0  6  d
1  1  c
3  3  a
4  1  b

**2.4.3 排序**

In [184]:
print(df.sort_index())
print('*'*20)
print(df.sort_index(ascending=False))
print('*'*20)
print(df.sort_values('A', kind='quicksort', na_position='last'))  # mergesort / heapsort
print('*'*20)
print(df.sort_values(by=["A","B"], axis=0, ascending=[False,True]))
# 当存在多列或多行排序时，是有优先顺序的，根据列表中的优先顺序，在前面的优先级高，越往后优先级越低。

   A  B
0  6  d
1  1  c
2  1  c
3  3  a
4  1  b
********************
   A  B
4  1  b
3  3  a
2  1  c
1  1  c
0  6  d
********************
   A  B
1  1  c
2  1  c
4  1  b
3  3  a
0  6  d
********************
   A  B
0  6  d
3  3  a
4  1  b
1  1  c
2  1  c


**2.4.4 随机采样**

In [192]:
# NumPy乱序
arr = np.random.randint(0, 10, size=(3,4))
print(arr)
np.random.shuffle(arr)
arr

[[6 2 1 8]
 [0 5 8 3]
 [6 4 1 4]]


array([[0, 5, 8, 3],
       [6, 2, 1, 8],
       [6, 4, 1, 4]])

In [197]:
# NumPy乱序2
arr1 = np.random.randint(0, 10, size=(3,4))
print(arr1)
print(np.random.permutation(arr1))
print(arr1)
print(np.random.permutation(10))

[[2 5 5 1]
 [0 0 3 9]
 [7 1 3 1]]
[[0 0 3 9]
 [2 5 5 1]
 [7 1 3 1]]
[[2 5 5 1]
 [0 0 3 9]
 [7 1 3 1]]
[7 0 5 8 1 4 9 6 3 2]


In [214]:
# DataFrame乱序
print(df.take(np.random.permutation(np.arange(2,5))))
print(df.take(np.random.permutation(3),axis=0))
print(df.take(np.random.permutation(2),axis=1))

   A  B
4  1  b
3  3  a
2  1  c
   A  B
2  1  c
0  6  d
1  1  c
   A  B
0  6  d
1  1  c
2  1  c
3  3  a
4  1  b


**2.4.5 替换**

In [217]:
# 单值替换
df.replace(1, 10)

A  B
0   6  d
1  10  c
2  10  c
3   3  a
4  10  b

In [218]:
# 多值替换
df.replace([3, 6], [True, False])

A  B
0  False  d
1     10  c
2     10  c
3   True  a
4     10  b

**2.4.6 映射与运算**

In [221]:
df = pd.DataFrame({'ticker': ['aapl', 'amz', 'ibm'], 'price': [11,22,33]})
tick2name = {'aapl': 'Apple inc', 'amz': 'Amazon Tech co.', 'ibm': 'International Business Machines Corporation'}
df['name'] = df['ticker'].map(tick2name)
df

ticker  price                                         name
0   aapl     11                                    Apple inc
1    amz     22                              Amazon Tech co.
2    ibm     33  International Business Machines Corporation

In [224]:
# 并不是任何形式的函数都可以作为map的参数.只有当一个函数具有一个参数且有返回值,那么该函数才可以作为map的参数
df['price2'] = df['price'].map(lambda x: x*x if x < 22 else x*2)
df

ticker  price                                         name  price2
0   aapl     11                                    Apple inc     121
1    amz     22                              Amazon Tech co.      44
2    ibm     33  International Business Machines Corporation      66

In [249]:
def test_func(x):
    price, name = x['price'], x['name']
    return price*price if price <= 22 and name=='Amazon Tech co.' else price*2

In [250]:
# 大数据运算使用apply
df['price2'] = df[['price', 'name']].apply(test_func, axis=1)
df

ticker  price                                         name  price2
0   aapl     11                                    Apple inc      22
1    amz     22                              Amazon Tech co.     484
2    ibm     33  International Business Machines Corporation      66

### 2.4 DataFrame的分组聚合操作

**2.4.1 基本操作**

In [269]:
df = pd.read_csv('./data/all_stocks.csv')
df

date   open   high    low  close    volume Name
0       2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1       2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2       2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3       2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4       2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL
...            ...    ...    ...    ...    ...       ...  ...
619035  2018-02-01  76.84  78.27  76.69  77.82   2982259  ZTS
619036  2018-02-02  77.53  78.12  76.73  76.78   2595187  ZTS
619037  2018-02-05  76.64  76.92  73.18  73.83   2962031  ZTS
619038  2018-02-06  72.74  74.56  72.13  73.27   4924323  ZTS
619039  2018-02-07  72.70  75.00  72.69  73.86   4534912  ZTS

[619040 rows x 7 columns]

In [271]:
# 5年内最高价
df.groupby(by="Name")['high'].max()

# std(标准差)、median(中位数)、min(最小值)、max(最大值)、mean(均值)

Name
A        75.00
AAL      59.08
AAP     201.24
AAPL    180.10
ABBV    125.86
         ...  
XYL      76.81
YUM      95.90
ZBH     133.49
ZION     55.61
ZTS      80.13
Name: high, Length: 505, dtype: float64

In [275]:
# 查看分组情况
df.groupby(by="Name").groups

{'A': [71611, 71612, 71613, 71614, 71615, 71616, 71617, 71618, 71619, 71620, 71621, 71622, 71623, 71624, 71625, 71626, 71627, 71628, 71629, 71630, 71631, 71632, 71633, 71634, 71635, 71636, 71637, 71638, 71639, 71640, 71641, 71642, 71643, 71644, 71645, 71646, 71647, 71648, 71649, 71650, 71651, 71652, 71653, 71654, 71655, 71656, 71657, 71658, 71659, 71660, 71661, 71662, 71663, 71664, 71665, 71666, 71667, 71668, 71669, 71670, 71671, 71672, 71673, 71674, 71675, 71676, 71677, 71678, 71679, 71680, 71681, 71682, 71683, 71684, 71685, 71686, 71687, 71688, 71689, 71690, 71691, 71692, 71693, 71694, 71695, 71696, 71697, 71698, 71699, 71700, 71701, 71702, 71703, 71704, 71705, 71706, 71707, 71708, 71709, 71710, ...], 'AAL': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 7

In [282]:
# 使用groupby分组后,也可以使用transform和apply提供自定义函数实现更多的运算
# transform() 里面不能跟自定义的特征交互函数，因为transform是真针对每一元素（即每一列特征操作）进行计算
print(df.groupby(by="Name")['close'].apply(lambda x: x.mean()))
print(df.groupby(by="Name")['close'].transform(lambda x: x.mean()))

Name
A        49.202025
AAL      38.393252
AAP     132.433463
AAPL    109.066698
ABBV     60.864440
           ...    
XYL      41.434095
YUM      75.451009
ZBH     105.606291
ZION     32.171790
ZTS      45.098648
Name: close, Length: 505, dtype: float64
0         38.393252
1         38.393252
2         38.393252
3         38.393252
4         38.393252
            ...    
619035    45.098648
619036    45.098648
619037    45.098648
619038    45.098648
619039    45.098648
Name: close, Length: 619040, dtype: float64


**2.4.2 aggregate聚合操作**  
在对数据进行分组之后，可以对分组后的数据进行聚合处理统计

In [286]:
df.groupby(by="Name").get_group('AAPL').agg({"volume": ['median', 'mean','max'], "close": ['median', 'mean','max']})

volume       close
median  4.566893e+07  109.010000
mean    5.404790e+07  109.066698
max     2.668336e+08  179.260000

### 2.5 DataFrame数据透视表与交叉表

**2.5.1 DataFrame数据透视**

这个数据透视表跟Excel中的数据透视功能是一样的，也是分组计算的一种方式，只能这种方式比groupby更加方便快捷，可操作性强，灵活好用。

In [288]:
df.pivot_table(index='Name', values=['volume','close'], aggfunc=['median', 'mean'])

median                    mean              
       close      volume       close        volume
Name                                              
A      46.70   2003109.0   49.202025  2.338039e+06
AAL    40.87   8111323.0   38.393252  9.390321e+06
AAP   141.30    849135.0  132.433463  1.078043e+06
AAPL  109.01  45668931.0  109.066698  5.404790e+07
ABBV   60.17   6707435.0   60.864440  7.870683e+06
...      ...         ...         ...           ...
XYL    37.28   1063287.0   41.434095  1.183141e+06
YUM    74.10   2665015.0   75.451009  3.209032e+06
ZBH   105.97   1128269.0  105.606291  1.297144e+06
ZION   29.23   2326445.0   32.171790  2.621178e+06
ZTS    45.62   3014964.0   45.098648  3.681878e+06

[505 rows x 4 columns]

**2.5.1 DataFrame交叉表**

In [289]:
pd.crosstab(df['Name'], df['date'])

date  2013-02-08  2013-02-11  2013-02-12  2013-02-13  2013-02-14  2013-02-15  \
Name                                                                           
A              1           1           1           1           1           1   
AAL            1           1           1           1           1           1   
AAP            1           1           1           1           1           1   
AAPL           1           1           1           1           1           1   
ABBV           1           1           1           1           1           1   
...          ...         ...         ...         ...         ...         ...   
XYL            1           1           1           1           1           1   
YUM            1           1           1           1           1           1   
ZBH            1           1           1           1           1           1   
ZION           1           1           1           1           1           1   
ZTS            1           1           1           1           1           1   

date  2013-02-19  2013-02-20  2013-02-21  2013-02-22  ...  2018-01-25  \
Name                                                  ...               
A              1           1           1           1  ...           1   
AAL            1           1           1           1  ...           1   
AAP            1           1           1           1  ...           1   
AAPL           1           1           1           1  ...           1   
ABBV           1           1           1           1  ...           1   
...          ...         ...         ...         ...  ...         ...   
XYL            1           1           1           1  ...           1   
YUM            1           1           1           1  ...           1   
ZBH            1           1           1           1  ...           1   
ZION           1           1           1           1  ...           1   
ZTS            1           1           1           1  ...           1   

date  2018-01-26  2018-01-29  2018-01-30  2018-01-31  2018-02-01  2018-02-02  \
Name                                                                           
A              1           1           1           1           1           1   
AAL            1           1           1           1           1           1   
AAP            1           1           1           1           1           1   
AAPL           1           1           1           1           1           1   
ABBV           1           1           1           1           1           1   
...          ...         ...         ...         ...         ...         ...   
XYL            1           1           1           1           1           1   
YUM            1           1           1           1           1           1   
ZBH            1           1           1           1           1           1   
ZION           1           1           1           1           1           1   
ZTS            1           1           1           1           1           1   

date  2018-02-05  2018-02-06  2018-02-07  
Name                                      
A              1           1           1  
AAL            1           1           1  
AAP            1           1           1  
AAPL           1           1           1  
ABBV           1           1           1  
...          ...         ...         ...  
XYL            1           1           1  
YUM            1           1           1  
ZBH            1           1           1  
ZION           1           1           1  
ZTS            1           1           1  

[505 rows x 1259 columns]

## 练习三

In [138]:
## 练习1： 有一列整数列A的DatraFrame，删除数值重复的行
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
print(df.loc[df['A'].shift() != df['A']])
print(df.drop_duplicates(subset='A', keep='first'))

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7
   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7


In [142]:
## 练习2：一个有5列的DataFrame，求哪一列的和最小，并打印数值
df = pd.DataFrame(np.random.random(size=(5, 5)))
print(df)
df.sum().min()

          0         1         2         3         4
0  0.541865  0.113240  0.530049  0.522619  0.803997
1  0.886212  0.768004  0.059485  0.312230  0.117682
2  0.692181  0.140411  0.532093  0.535103  0.165331
3  0.247924  0.973966  0.062325  0.164152  0.377052
4  0.028942  0.138548  0.684222  0.806096  0.167630


1.6316912548406726

In [183]:
## 练习3：将Name列中的AAPL替换为Apple
df = pd.read_csv('./data/all_stocks.csv')
df.replace('AAPL', 'Apple')

date   open   high    low  close    volume Name
0       2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1       2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2       2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3       2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4       2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL
...            ...    ...    ...    ...    ...       ...  ...
619035  2018-02-01  76.84  78.27  76.69  77.82   2982259  ZTS
619036  2018-02-02  77.53  78.12  76.73  76.78   2595187  ZTS
619037  2018-02-05  76.64  76.92  73.18  73.83   2962031  ZTS
619038  2018-02-06  72.74  74.56  72.13  73.27   4924323  ZTS
619039  2018-02-07  72.70  75.00  72.69  73.86   4534912  ZTS

[619040 rows x 7 columns]

In [165]:
## 练习4：在df中插入行，然后删除它
index = len(df) + 1
df.loc[index] = ['2022-06-27', 23, 34, 54, 23, 342552, 'JINQIAO']
print(df)
df.drop(index)

              date   open   high    low  close    volume     Name
0       2013-02-08  15.07  15.12  14.63  14.75   8407500      AAL
1       2013-02-11  14.89  15.01  14.26  14.46   8882000      AAL
2       2013-02-12  14.45  14.51  14.10  14.27   8126000      AAL
3       2013-02-13  14.30  14.94  14.25  14.66  10259500      AAL
4       2013-02-14  14.94  14.96  13.16  13.99  31879900      AAL
...            ...    ...    ...    ...    ...       ...      ...
619036  2018-02-02  77.53  78.12  76.73  76.78   2595187      ZTS
619037  2018-02-05  76.64  76.92  73.18  73.83   2962031      ZTS
619038  2018-02-06  72.74  74.56  72.13  73.27   4924323      ZTS
619039  2018-02-07  72.70  75.00  72.69  73.86   4534912      ZTS
619041  2022-06-27  23.00  34.00  54.00  23.00    342552  JINQIAO

[619041 rows x 7 columns]


date   open   high    low  close    volume Name
0       2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1       2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2       2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3       2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4       2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL
...            ...    ...    ...    ...    ...       ...  ...
619035  2018-02-01  76.84  78.27  76.69  77.82   2982259  ZTS
619036  2018-02-02  77.53  78.12  76.73  76.78   2595187  ZTS
619037  2018-02-05  76.64  76.92  73.18  73.83   2962031  ZTS
619038  2018-02-06  72.74  74.56  72.13  73.27   4924323  ZTS
619039  2018-02-07  72.70  75.00  72.69  73.86   4534912  ZTS

[619040 rows x 7 columns]

In [167]:
# 练习5：将high列中的大于50的值替换为布尔值True, 繁殖False
df['high'] = df['high'].map(lambda x: x > 50)
df

date   open   high    low  close    volume     Name
0       2013-02-08  15.07  False  14.63  14.75   8407500      AAL
1       2013-02-11  14.89  False  14.26  14.46   8882000      AAL
2       2013-02-12  14.45  False  14.10  14.27   8126000      AAL
3       2013-02-13  14.30  False  14.25  14.66  10259500      AAL
4       2013-02-14  14.94  False  13.16  13.99  31879900      AAL
...            ...    ...    ...    ...    ...       ...      ...
619036  2018-02-02  77.53   True  76.73  76.78   2595187      ZTS
619037  2018-02-05  76.64   True  73.18  73.83   2962031      ZTS
619038  2018-02-06  72.74   True  72.13  73.27   4924323      ZTS
619039  2018-02-07  72.70   True  72.69  73.86   4534912      ZTS
619041  2022-06-27  23.00  False  54.00  23.00    342552  JINQIAO

[619041 rows x 7 columns]